language: node_js

node_js:
  - "8.12"

before_install:
  - chmod a+x ./scripts/*.sh

install:
  - ./scripts/setup.sh

script:
  - ls
  - cd ./Scripting_Manual_JCSUnity
  - ./scripts/start_forever.sh
  - ./scripts/stop_forever.sh
